import { Geist, Geist_Mono, Style_Script } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const styleScript = Style_Script({
  subsets: ['latin'],
  weight: '400', // Style Script only has 400
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${styleScript.variable} antialiased text-[#212121]`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
